// <auto-generated />
namespace CoDelivery.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Arriba3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arriba3));
        
        string IMigrationMetadata.Id
        {
            get { return "201503210405268_Arriba3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
